routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\CarCat;
use App\CarModel;
use App\Color;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth/login2');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', function () {
    return view('administrator');
});

Route::resource('/cars', 'CarsController');


Route::get('/map', function () {
    return view('map');
});

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $guarded = [];

    public function model()
    {
        return $this->belongsTo('App\CarModel', 'model_id');
    }

    public function color()
    {
        return $this->belongsTo('App\Color', 'color_id');
    }

    public function car_type()
    {
        return $this->belongsTo('App\CarCat', 'carcat_id');
    }

    public function fuel_type()
    {
        if ($this->fuel_type == 1) return 'АИ-92';
        elseif ($this->fuel_type == 2) return 'АИ-95';
        elseif ($this->fuel_type == 3) return 'АИ-98';
        return 'АИ-100, 101, 102';
    }

    public function transmission()
    {
        if ($this->gearbox_type == 1) return 'Механическая коробка';
        elseif ($this->gearbox_type == 2) return 'Автоматическая коробка';
        elseif ($this->gearbox_type == 3) return 'Роботизированная коробка';
        return 'Вариативная коробка';
    }

}

app/CarCat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CarCat extends Model
{
    protected $table = 'carcat';
    protected $guarded = [];
}

app/CarModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CarModel extends Model
{
    protected $table = 'car_models';
    protected $guarded = [];

    public function manufacturer()
    {
        return $this->belongsTo('App\Manufacturer', 'id_manufacturer');
    }
}

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    protected $table = 'colors';
    protected $guarded = [];
}

app/Manufacturer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manufacturer extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'password', 'phone', 'email', 'last_login_date', 'last_login_ip'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function profile()
    {
        return $this->hasOne(UserProfile::class);
    }
}

app/UserProfile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserProfile extends Model
{
    //
}

app/Http/Controllers/CarsController.php
<?php

namespace App\Http\Controllers;

use App\Car;
use App\CarCat;
use App\CarModel;
use App\Color;
use Illuminate\Http\Request;

class CarsController extends Controller
{
    public function index()
    {
        $cars = \App\Car::all();
        return view('cars.index', compact('cars'));
    }

    public function create()
    {
        $carModels = CarModel::with('manufacturer')->get();
        $colors = Color::all();
        $carcat = CarCat::all();
        $transmissions = array(
            ['id' => 1, 'name' => 'Механическая коробка'],
            ['id' => 2, 'name' => 'Автоматическая коробка'],
            ['id' => 3, 'name' => 'Роботизированная коробка'],
            ['id' => 4, 'name' => 'Вариативная коробка'],
        );
        $transmissions = json_decode(json_encode($transmissions));

        $fuelTypes = array(
            ['id' => 1, 'name' => 'АИ-92'],
            ['id' => 2, 'name' => 'АИ-95'],
            ['id' => 3, 'name' => 'АИ-98'],
            ['id' => 4, 'name' => 'АИ-100, 101, 102'],
        );
        $fuelTypes = json_decode(json_encode($fuelTypes));

        return view('cars.create', compact('carModels', 'colors', 'carcat', 'transmissions', 'fuelTypes'));
    }

    public function store(Request $request)
    {
        \App\Car::create([
            'model_id' => $request->model,
            'gov_number' => $request->number,
            'color_id' => $request->color,
            'gearbox_type' => $request->transmission,
            'fuel_type' => $request->fuel_type,
            'fuel_cons' => $request->consumption,
            'carcat_id' => $request->carcat,
        ]);
        return redirect(route('cars.index'));
    }

    public function edit(Car $car)
    {
        $carModels = CarModel::with('manufacturer')->get();
        $colors = Color::all();
        $carcat = CarCat::all();
        $transmissions = array(
            ['id' => 1, 'name' => 'Механическая коробка'],
            ['id' => 2, 'name' => 'Автоматическая коробка'],
            ['id' => 3, 'name' => 'Роботизированная коробка'],
            ['id' => 4, 'name' => 'Вариативная коробка'],
        );
        $transmissions = json_decode(json_encode($transmissions));

        $fuelTypes = array(
            ['id' => 1, 'name' => 'АИ-92'],
            ['id' => 2, 'name' => 'АИ-95'],
            ['id' => 3, 'name' => 'АИ-98'],
            ['id' => 4, 'name' => 'АИ-100, 101, 102'],
        );
        $fuelTypes = json_decode(json_encode($fuelTypes));

        return view('cars.edit', compact('car', 'carModels', 'colors', 'carcat', 'transmissions', 'fuelTypes'));
    }

    public function update(Request $request, Car $car)
    {
        $car->update([
            'model_id' => $request->model,
            'gov_number' => $request->number,
            'color_id' => $request->color,
            'gearbox_type' => $request->transmission,
            'fuel_type' => $request->fuel_type,
            'fuel_cons' => $request->consumption,
            'carcat_id' => $request->carcat,
        ]);
        return redirect(route('cars.index'));
    }

    public function show()
    {

    }

    public function destroy(Car $car)
    {
        $car->delete();
        return redirect(route('cars.index'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('map');
    }
}

resources/views/administrator.blade.php
@extends('layouts.base')

@section('content')
    @include('menu')
    <div class="content">
        <h1>Администратор</h1>

        <div class="tabs">
            <div class="tab-item" onclick="openCity('users')">Пользователи</div>
            <div class="tab-item" onclick="openCity('car-wash')">Автомойки</div>
            <div class="tab-item" onclick="openCity('trips')">Поездки</div>
            <div class="tab-item" onclick="openCity('settings')">Настройки</div>
        </div>

        <div id="users" class="tab-content">
            <table class="table">
                <thead>
                <th>ID</th>
                <th>ФИО</th>
                <th>Логин</th>
                <th>Статус</th>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>Шмелев Дмитрий Е</td>
                    <td>admin</td>
                    <td class="active">Активен</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Федерякина Полина С</td>
                    <td>admin</td>
                    <td class="active">Активен</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Шацких Даниил А</td>
                    <td>admin</td>
                    <td class="active">Активен</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Шмелев Дмитрий Е</td>
                    <td>admin</td>
                    <td>Активен</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div id="car-wash" class="tab-content" style="display:none">
            <h1>Автомойки</h1>
        </div>

        <div id="trips" class="tab-content" style="display:none">
            <h1>Поездки</h1>
        </div>

        <div id="settings" class="tab-content" style="display:none">
            <h1>Настройки</h1>
        </div>
    </div>

    <script>
        function openCity(tabContent) {
            var i;
            var x = document.getElementsByClassName("tab-content");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            document.getElementById(tabContent).style.display = "block";
        }
    </script>
@endsection

resources/views/cars/create.blade.php
@extends('layouts.base')

@section('content')
    @include('menu')
    <div class="content">
        <h1>Добавление автомобиля</h1>
        <form action="{{ route('cars.store') }}" method="post" class="authform">
            {{ csrf_field() }}

            <label for="model">Модель</label>
            <select name="model" id="model" class="form-control">
                @foreach($carModels as $carModel)
                    <option value="{{ $carModel->id }}">{{ $carModel->manufacturer->manufacturer_name  }} {{ $carModel->model_name }}</option>
                @endforeach
            </select>
            <input name="number" type="text" placeholder="Номер автомобиля">

            <label for="color">Цвет</label>
            <select name="color" id="color" class="form-control">
                @foreach($colors as $color)
                    <option value="{{ $color->id }}">{{ $color->color_name }}</option>
                @endforeach
            </select>

            <label for="transmission">Тип КПП</label>
            <select name="transmission" id="transmission" class="form-control">
                @foreach($transmissions as $transmission)
                    <option value="{{ $transmission->id }}">{{ $transmission->name }}</option>
                @endforeach
            </select>

            <label for="fuel_type">Тип топлива</label>
            <select name="fuel_type" id="fuel_type" class="form-control">
                @foreach($fuelTypes as $fuelType)
                    <option value="{{ $fuelType->id }}">{{ $fuelType->name }}</option>
                @endforeach
            </select>

            <input name="consumption" type="text" placeholder="Потребление топлива">

            <label for="carcat">Классы машины</label>
            <select name="carcat" id="carcat" class="form-control">
                @foreach($carcat as $cat)
                    <option value="{{ $cat->id }}">{{ $cat->carcat_name }}</option>
                @endforeach
            </select>
            <button type="submit">Добавить</button>
        </form>
    </div>
@endsection

resources/views/cars/edit.blade.php
@extends('layouts.base')

@section('content')
    @include('menu')
    <div class="content">
        <h1>Редактирование автомобиля</h1>
        <form action="{{ route('cars.update', $car) }}" method="post" class="authform">
            {!! method_field('patch') !!}
            {!! csrf_field() !!}

            <div>
                <label for="model">Модель</label>
                <select name="model" id="model" class="form-control">
                    @foreach($carModels as $carModel)
                        @if($carModel->id == $car->model_id)
                            <option selected
                                    value="{{ $carModel->id }}">{{ $carModel->manufacturer->manufacturer_name  }} {{ $carModel->model_name }}</option>
                        @else
                            <option value="{{ $carModel->id }}">{{ $carModel->manufacturer->manufacturer_name  }} {{ $carModel->model_name }}</option>
                        @endif
                    @endforeach
                </select>
            </div>

            <div>
                <input name="number" type="text" placeholder="Номер автомобиля" value="{{ $car->gov_number }}">
            </div>

            <div>
                <label for="color">Цвет</label>
                <select name="color" id="color" class="form-control">
                    @foreach($colors as $color)
                        @if($color->id == $car->color_id)
                            <option selected value="{{ $color->id }}">{{ $color->color_name }}</option>
                        @else
                            <option value="{{ $color->id }}">{{ $color->color_name }}</option>
                        @endif
                    @endforeach
                </select>
            </div>

            <div>
                <label for="transmission">Тип КПП</label>
                <select name="transmission" id="transmission" class="form-control">
                    @foreach($transmissions as $transmission)
                        @if($transmission->id == $car->gearbox_type)
                            <option selected value="{{ $transmission->id }}">{{ $transmission->name }}</option>
                        @else
                            <option value="{{ $transmission->id }}">{{ $transmission->name }}</option>
                        @endif
                    @endforeach
                </select>
            </div>

            <div>
                <label for="fuel_type">Тип топлива</label>
                <select name="fuel_type" id="fuel_type" class="form-control">
                    @foreach($fuelTypes as $fuelType)
                        @if($fuelType->id == $car->fuel_type)
                            <option selected value="{{ $fuelType->id }}">{{ $fuelType->name }}</option>
                        @else
                            <option value="{{ $fuelType->id }}">{{ $fuelType->name }}</option>
                        @endif
                    @endforeach
                </select>
            </div>

            <div>
                <input name="consumption" type="text" placeholder="Потребление топлива" value="{{ $car->fuel_cons }}">
            </div>

            <div>
                <label for="carcat">Классы машины</label>
                <select name="carcat" id="carcat" class="form-control">
                    @foreach($carcat as $cat)
                        @if($cat->id == $car->carcat_id)
                            <option selected value="{{ $cat->id }}">{{ $cat->carcat_name }}</option>
                        @else
                            <option value="{{ $cat->id }}">{{ $cat->carcat_name }}</option>
                        @endif
                    @endforeach
                </select>
            </div>
            <button type="submit">Сохранить</button>
        </form>
    </div>
@endsection

resources/views/cars/index.blade.php
@extends('layouts.base')

@section('content')
    @include('menu')
    <div class="content">
        <h1>Список автомобилей</h1>
        <table class="table">
            <thead>
                <th>Модель</th>
                <th>Номер</th>
                <th>Цвет</th>
                <th>Тип КПП</th>
                <th>Тип топлива</th>
                <th>Потребление топлива</th>
                <th>Класс машины</th>
            </thead>
            <tbody>
            @foreach($cars as $car)
                <tr>
                    <td>{{ $car->model->manufacturer->manufacturer_name }} {{ $car->model->model_name }}</td>
                    <td>{{ $car->gov_number }}</td>
                    <td>{{ $car->color->color_name }}</td>
                    <td>{{ $car->transmission() }}</td>
                    <td>{{ $car->fuel_type() }}</td>
                    <td>{{ $car->fuel_cons }}</td>
                    <td>{{ $car->car_type['carcat_name'] }}</td>
                    <td>
                        <a href="{{ route('cars.edit', $car) }}">Редактировать</a>
                    </td>
                    <td>
                        <form action="{{ route('cars.destroy', $car) }}" method="POST">
                            <input name="_car_id" type="hidden"  value="{{$car->id}}">
                            <button type="submit">Удалить</button>
                            {!! method_field('delete') !!}
                            {!! csrf_field() !!}
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->profile->fam ?? '...' }} {{ Auth::user()->profile->nam ?? '...' }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="../css/auth_style.css">
</head>
<body>
    @yield('content')
</body>


</html>

resources/views/map.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <title>Карта</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
</head>
<body>
@include('menu')
<div class="content content-map">
    <div id="mapid">
        <div class="map-car" style="left: 15%; top: 25%; transform: rotate(-32.36deg);"></div>
        <div class="map-car" style="left: 70%; top: 60%; transform: rotate(62.36deg);"></div>
        <div class="map-car" style="left: 30%; top: 33%;"></div>
    </div>
</div>
</body>

<script>

    var mymap = L.map('mapid').setView([51.505, -0.09], 13);

    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
        maxZoom: 18,
        id: 'mapbox/streets-v11'
    }).addTo(mymap);

</script>
</html>

resources/views/menu.blade.php
<div class="menu">
    <div class="menu-profile">
        <div class="menu-profile-name">Дмитрий Шмелёв</div>
        <div class="menu-logout">Выход</div>
    </div>
    <a class="menu-item profile" href="{{ route('register') }}">Регистрация</a>
    <a class="menu-item profile" href="{{ route('login') }}">Вход</a>
    <a class="menu-item profile" href="/home">Мой профиль</a>
    <a class="menu-item car" href="/map">Арендовать авто</a>
    <a class="menu-item profile" href="/admin">Администратор</a>
    <a class="menu-item car" href="{{ route('cars.create') }}">Добавить авто</a>
    <a class="menu-item car" href="{{ route('cars.index') }}">Список авто</a>
</div>